CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

IGNORE_INDEX = -100

DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IM_START_TOKEN = "[IMG]"
DEFAULT_IM_END_TOKEN = "[/IMG]"


# IMAGE_TOKEN_IDX = 151667
T2I_TOKEN_IDX = 151666
I2I_TOKEN_IDX = 151667



UND_IMAGE_TOKEN = "<|image_pad|>"
UND_IMAGE_TOKEN_IDX = 151655
